eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

microservices:
  product-service:
    endpoints:
      endpoint:
        uri: http://product-service/payment/doPayment
  order-service:
    endpoints:
      endpoint:
        uri: http://product-service/payment/doPayment
